// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWODANgzjVAKEr3Gwx1LKtLvjmNNSjF4U',
    appId: '1:465626200526:web:a1158accb98d2fa5b4139f',
    messagingSenderId: '465626200526',
    projectId: 'istart-b8414',
    authDomain: 'istart-b8414.firebaseapp.com',
    databaseURL: 'https://istart-b8414-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'istart-b8414.appspot.com',
    measurementId: 'G-JTW4GWNHE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRvSQUgQr53qQ-8doIhprthKjzwZiTDVM',
    appId: '1:465626200526:android:c01999ee3ba2f142b4139f',
    messagingSenderId: '465626200526',
    projectId: 'istart-b8414',
    databaseURL: 'https://istart-b8414-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'istart-b8414.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9F0aaSCwjVadqGBkqYWyttXhF2dVrxvk',
    appId: '1:465626200526:ios:170f32f3dfd26448b4139f',
    messagingSenderId: '465626200526',
    projectId: 'istart-b8414',
    databaseURL: 'https://istart-b8414-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'istart-b8414.appspot.com',
    androidClientId: '465626200526-8moaoei8hgfqkd0124ao2svb9to9oujs.apps.googleusercontent.com',
    iosClientId: '465626200526-eb4adh4gg4oqh6tlj8pilglkspk7c0ef.apps.googleusercontent.com',
    iosBundleId: 'com.example.istart',
  );
}
